// This file is automatically generated: DO NOT EDIT.
// To change this value, create a camera.json file in the
// distribution directory with content like this: 
//   { "maxImagePixelSize": 6000000 }
var CONFIG_MAX_IMAGE_PIXEL_SIZE = 5242880;